if (!window.g_loc) {
    g_loc = {
        loctext : {}
    };
}

g_loc.loctext = {
    "interfaces.description" : "Description",
    "interfaces.receive" : "Messages \"{1}\" Can Receive",
    "interfaces.receivehelp" : "<u>Click the Code Blocks</u> below and see how \"{1}\" responds.",
    "interfaces.send" : "Messages \"{1}\" Can Send",
    "interfaces.properties" : "Properties",
    "properties.helpdescription" : "Enter something that describes your project.",
    "help.background" : "How the background image should fit on the stage",
    "properties.background_image" : "Background Image",
    "properties.bgtype_normal" : "Normal",
    "properties.bgtype_stretch" : "Stretch",
    "properties.bgtype_tile" : "Tile",
    "properties.bgwidth" : "Width",
    "properties.bgheight" : "Height",
    "properties.bgexpand" : "Automatically expand canvas",
    "properties.enable_tilemap" : "Enable Tilemap",
    "help.enable_tilemap" : "Turn on the tilemap",
    "properties.enable_bgscroll" : "Enable Background Scroll",
    "help.enable_bgscroll" : "Turn on the background scrolling to sync with tilemap scrolling",
    "properties.tilemapsize" : "World Size",
    "help.tilemapsize" : "Specify the world size as number of tiles horizontally and vertically.",
    "properties.enable_physics" : "Enable Physics",
    "properties.gravity" : "Gravity",
    "help.physics" : "Turn on whether objects interact using physics",
    "help.gravity" : "Positive values apply gravity falling towards the bottom right.  Negative values apply gravity towards the upper left.",
    "properties.direction" : "Direction",
    "properties.scale" : "Scale",
    "properties.rotate_freely" : "Rotate Freely",
    "properties.flip_horizontally" : "Flip Horizontally",
    "properties.dont_rotate" : "Don't Rotate",
    "properties.allow_dragging" : "Allow dragging while stage is playing",
    "properties.material" : "Material",
    "help.material" : "Choose a preset of friction and bounciness values. Friction makes the objects slow down if the slide against each other. Bounciness makes the objects bound. A value of 1.0 means that a ball will bounce back to the same height from which it was dropped, which a value of 0 means it will not bounce at all. Mass determines how heavy the object is.",
    "properties.mat_custom" : "Custom",
    "properties.mat_wood" : "Wood",
    "properties.mat_metal" : "Metal",
    "properties.mat_stone" : "Stone",
    "properties.mat_plastic" : "Plastic",
    "properties.mat_rubber" : "Rubber",
    "properties.mat_deadweight" : "Dead Weight",
    "properties.mat_superball" : "Superball",
    "properties.friction" : "Friction",
    "properties.restitution" : "Bounciness",
    "properties.mass" : "Weight",
    "properties.geometry" : "Geometry",
    "help.geometry" : "Select the closest shape that matches the image",
    "properties.shape_circular" : "Circular",
    "properties.shape_rectangular" : "Rectangular",
    "properties.static" : "Is Static",
    "properties.active" : "Is Active",
    "button.unlock_tblock" : "Unlock T.Block",
    "button.tab_costumes" : "Costumes",
    "button.tab_scenes" : "Backgrounds",
    "title.backpack" : "Backpack",
    "backpack.empty" : "<img src=\"/image/troll/troll-idehelp-backpack.png\"/>Hi! Did you know you can <b>drag code blocks</b> and <b>actors</b> here to <b>save</b> them and <b>use them in any of your projects</b>?<br/>Try it now!",
    "title.paint" : "Create Image",
    "title.paint_create_actor" : "Create an Image for a New Actor",
    "title.paint_create_costume" : "Create a New Costume for {1}",
    "title.paint_create_bg" : "Create a New Background",
    "title.paint_edit_costume" : "Edit Costume for {1}",
    "title.paint_edit_bg" : "Edit Background for Stage",
    "title.name" : "Name",
    "title.value" : "Value",
    "title.description" : "Description",
    "title.instructions" : "Instructions",
    "title.details" : "Details",
    "button.showme" : "Show Me",
    "button.dothisforme" : "Do This For Me",
    "button.preview" : "Play",
    "button.done" : "Done",
    "title.concepts" : "Concepts",
    "notes.description" : "Description",
    "notes.accepts_messages" : "Accepts Messages",
    "notes.sends_messages" : "Sends Messages",
    "notes.properties" : "Properties",
    "menu.open_project" : "Open Project",
    "menu.new_project" : "New Project",
    "menu.save_project" : "Save Project",
    "menu.edit_project" : "Edit Project Details",
    "menu.save_project_as" : "Save Project As...",
    "menu.autosave_on" : "Turn Auto-Save On",
    "menu.autosave_off" : "Turn Auto-Save Off",
    "menu.create_lesson" : "Generate Tutorial",
    "menu.run_lesson" : "Play Tutorial",
    "menu.create_puzzle" : "Create Puzzle",
    "menu.create_quiz" : "Create Quiz",
    "menu.create_lesson_bundle" : "Create Lesson Bundle",
    "menu.create_project_bundle" : "Create Project Bundle",
    "menu.addannotation" : "Add Tutorial Note",
    "menu.annotate" : "Create Tutorial",
    "menu.editannotate" : "Edit Tutorial",
    "menu.annotationhelp" : "Tutorial Help",
    "menu.hideannotate" : "Hide Tutorial",
    "menu.showannotate" : "Show Tutorial",
    "menu.resetall" : "Reset Actors",
    "menu.codesearch" : "Find Block",
    "menu.undo" : "Undo",
    "menu.redo" : "Redo",
    "menu.delete" : "Delete",
    "menu.cut" : "Cut",
    "menu.copy" : "Copy",
    "menu.paste" : "Paste",
    "menu.backpack" : "Backpack",
    "menu.savetblock" : "Save as TynkerBlock",
    "menu.unlocktblock" : "Unlock TynkerBlock",
    "menu.createblank" : "Add Blank Actor",
    "menu.createtext" : "Add Text Actor",
    "menu.cloneactor" : "Duplicate Actor",
    "menu.buildexpr" : "Build Expression",
    "dialog.buildexprtitle" : "Build Expression",
    "menu.importscript" : "Import as Script",
    "menu.exportscript" : "Export as Script",
    "menu.makewidget" : "Make Widget",
    "menu.makecrx" : "Make Chrome App",
    "menu.edittiles" : "Edit Tiles",
    "menu.rearrange" : "Rearrange Blocks Now",
    "menu.autorearrangenone" : "Manually Arrange Blocks",
    "menu.autorearrangebox" : "Auto Rearrange Blocks",
    "menu.autorearrangelinear" : "Auto Rearrange Blocks Linearly",
    "menu.file" : "File",
    "menu.edit" : "Edit",
    "menu.tools" : "Tools",
    "menu.movefront" : "Bring to Front",
    "menu.moveback" : "Send to Back",
    "menu.savedindicator" : "Saved {1} ago",
    "menu.submit" : "Turn In",
    "menu.debugger" : "Debugger",
    "menu.createlib" : "Create Library",
    "menu.loadlib" : "Include Library",
    "menu.search" : "Ask me a question and I can help you",
    "confirm.exit_unsaved1" : "You have 1 unsaved change. Save before leaving?",
    "confirm.exit_unsaved" : "You have {1} unsaved changes. Save before leaving?",
    "time.second" : "second",
    "time.seconds" : "seconds",
    "time.minute" : "minute",
    "time.minutes" : "minutes",
    "time.hour" : "hour",
    "time.hours" : "hours",
    "time.day" : "day",
    "time.days" : "days",
    "time.month" : "month",
    "time.months" : "months",
    "time.year" : "year",
    "time.years" : "years",
    "dialog.openprojecttitle" : "Open a Project",
    "newproject.name" : "Name",
    "newproject.placeholder" : "Enter project name",
    "newproject.createbtn" : "Create",
    "dialog.confirmlogout" : "Are you sure you want to save and log out?",
    "savedlg.project_name" : "Project Name:",
    "savedlg.default_my_project" : "My Project",
    "savedlg.description" : "Description:",
    "savedlg.descdetails" : "Say something about your project and tell how to play it!",
    "savedlg.share_project" : "Share Project",
    "savedlg.screenshot" : "Screenshot",
    "actorsavedlg.actor_name" : "Actor Name",
    "actorsavedlg.tags" : "Tags",
    "actorsavedlg.default_tags" : "Collections",
    "actorsavedlg.description" : "Description",
    "actorsavedlg.share" : "Share this actor",
    "actorsavedlg.icon" : "Icon",
    "libsavedlg.titlecreate" : "Create Library",
    "libsavedlg.titlesave" : "Save Library",
    "libsavedlg.name" : "Name",
    "libsavedlg.namespace" : "Namespace",
    "libsavedlg.description" : "Description",
    "libsavedlg.ispublic" : "Share this library",
    "var.scripttitle" : "Script Variables",
    "var.title_var" : "Create Variable",
    "var.title_varedit" : "Edit Variable",
    "var.title_list" : "Create List",
    "var.title_listedit" : "Edit List",
    "var.name" : "Variable Name",
    "var.listname" : "List Name",
    "var.doreset" : "Reset variable on stop",
    "var.default" : "Reset Value",
    "var.public" : "For all Actors",
    "var.local" : "For this Actor only",
    "var.cloud" : "Cloud variable (stored on server)",
    "var.btn_addvar" : "Add Variable",
    "func.name" : "Name:",
    "func.parameters" : "Parameters:",
    "func.btn_addparam" : "Add Parameter",
    "func.err_fnblank" : "The function name cannot be blank",
    "func.err_fndup" : "There is already a function with that name in this actor. You must enter a unique function name for this actor.",
    "func.err_paramblank" : "Parameter names cannot be blank.",
    "func.err_paramdup" : "There is already a parameter with the same name. Parameter names must be different for a function.",
    "title.help" : "Help",
    "progressdlg.wait" : "Loading... Please wait...",
    "confirmdlg.ask" : "Are you sure?",
    "alertdlg.ask" : "Alert",
    "winassets.confirmdelete" : "Are you sure you want to delete {1}?",
    "winassets.menusaveactor" : "Save T.Block",
    "winassets.menuunlockactor" : "Unlock T.Block",
    "winassets.hideinsandbox" : "Hide in Sandbox",
    "winassets.showinsandbox" : "Show in Sandbox",
    "winassets.lockinsandbox" : "Lock in Sandbox",
    "winassets.unlockinsandbox" : "Unlock in Sandbox",
    "winassets.actordialogtitle" : "Add an Actor",
    "winassets.adddraw" : "Draw Your Own",
    "winassets.addcharacter" : "Build a Character",
    "winassets.addlibrary" : "Add from Media Library",
    "winmedialib.addcostume" : "Add costume to actor",
    "winmedialib.addscene" : "Add scene to stage",
    "winmedialib.addactor" : "Add actor to stage",
    "winmedialib.addsoundtoactor" : "Add sound to actor",
    "winmedialib.addsoundtostage" : "Add sound to stage",
    "winlessons.confirmstepdelete" : "Are you sure you wish to remove the step?",
    "winlessons.btncreatenew" : "Create New",
    "winlessons.btnshowhideskip" : "Expand/Collapse Skip",
    "winlessons.btntoggleskip" : "Mark All Skip",
    "winlessons.btnaddcheckpoint" : "Add Checkpoint",
    "winlessons.btnaddfreeplay" : "Add Free Play",
    "winlessons.btnadddialog" : "Add Dialog",
    "winlessons.btneditexisting" : "Edit Existing",
    "winlessons.btnupdateexisting" : "Update Existing",
    "winlessons.btnremove" : "Remove Tutorial",
    "winlessons.btnclose" : "Close",
    "winlessons.btncancel" : "Cancel",
    "winlessons.btnsave" : "Save",
    "winlessons.btnsaveplay" : "Save & Play",
    "wintools.search" : "Search Code Blocks",
    "wintools.blocksused" : "{1} block in code",
    "wintools.blocksusedplural" : "{1} blocks in code",
    "wintools.disabledtooltip" : "These blocks are not applicable for the stage",
    "wintools.savebtn" : "Save library",
    "wintools.editbtn" : "Edit library",
    "wintools.deletebtn" : "Delete library from Tynker",
    "wintools.removebtn" : "Remove library from project",
    "wintools.deleteconfirm" : "Are you sure you want to delete this library? All projects that call this library will no longer work.",
    "wintools.removeconfirm" : "Remove library from this project?",
    "wincontent.progressimporting" : "Importing file...",
    "wincontent.confirmdelete" : "Are you sure you wish to delete? (Projects using this resource will have problems.)",
    "wincontent.selectactor" : "Media Library",
    "wincontent.selectcostumes" : "Media Library",
    "wincontent.selectbackgrounds" : "Media Library",
    "wincontent.selectsounds" : "Sound Library",
    "wincontent.defaultlabel" : "Created",
    "wincontent.emptycart" : "Click on images above to add",
    "wincontent.search" : "What are you searching for?",
    "winlessons.addcheckpointtext" : "Double-click to add a checkpoint note here",
    "winlessons.addnotetext" : "Double-click to add a note here",
    "winlessons.addfreeplaytext" : "Double-click to add a freeplay note here",
    "winlessons.adddialogtext" : "Double-click to add a dialog note here",
    "winlessons.addmilestonetext" : "Double-click to add a milestone note here",
    "winproperties.confirmunlock" : "Unlocking a TynkerBlock will merge your code with the TynkerBlock code.  This cannot be undone.  Are you sure you want to unlock?",
    "wincode.codeforlabel" : "Code for {1}",
    "wincode.funcoverwrite" : "Warning! An existing function with the same name already exists.  Do you wish to overwrite your old function?",
    "winproperties.confirmdeletecostume" : "Are you sure you want to delete the image named {1}?",
    "winproperties.confirmdeletesound" : "Are you sure you want to delete the sound named {1}?",
    "winstage.continuemsg" : "Click anywhere to continue",
    "lessontitle.bgimg" : "New Background",
    "lessontitle.bgsound" : "Sound for the Stage",
    "lessontitle.addtblock" : "New TynkerBlock Actor",
    "lessontitle.addsprite" : "New Actor",
    "lessontitle.addcostume" : "Costume for \"{1}\"",
    "lessontitle.addsound" : "Sound for \"{1}\"",
    "lessontitle.property" : "Change {1}'s Property",
    "lessontitle.addtolabelsocket" : "Code for \"{1}\"",
    "lessontitle.addtoblocksocket" : "Code for \"{1}\"",
    "lessontitle.label" : "Code for \"{1}\"",
    "lessontitle.labeltoblock" : "Code for \"{1}\"",
    "lessontitle.setvalue" : "Code for \"{1}\"",
    "lessontitle.block" : "Code for \"{1}\"",
    "lessontitle.blockcontainer" : "Code for \"{1}\"",
    "lessontitle.blocknext" : "Code for \"{1}\"",
    "generate.defaultlaststep" : "<p>When you are done with this activity, click the Play button to run it.</p>",
    "intlessontitle.bgimg" : "Add Background to Stage",
    "lessontext.bgimg" : "Click this button to add the <em class=\"value\">\"{1}\"</em> scene to the <em class=\"value\">Stage</em> from the <em>Media Library</em>.",
    "intlessontitle.bgsound" : "Add Sound to Stage",
    "lessontext.bgsound" : "Click this button to add the <em class=\"value\">\"{1}\"</em> sound to the <em class=\"value\">Stage</em> from the <em>Media Library</em>.",
    "intlessontitle.addcostume" : "Add Costume to Actor",
    "lessontext.addcostume" : "Click this button to add the <em class=\"value\">\"{2}\"</em> costume to the <em class=\"value\">\"{1}\"</em> actor from the <em>Media Library</em>.",
    "intlessontitle.addsprite" : "Add Actor to Stage",
    "lessontext.addsprite" : "Click this button to add the <em class=\"value\">\"{1}\"</em> actor to the <em class=\"value\">Stage</em> from the <em>Media Library</em>.",
    "intlessontitle.addsound" : "Add Sound to Actor",
    "lessontext.addsound" : "Click this button to add the <em class=\"value\">\"{2}\"</em> sound to the <em class=\"value\">\"{1}\"</em> actor from the <em>Media Library</em>.",
    "generate.bgimg" : "Add this <em>\"{1}\"</em> background to the <em>Stage</em>.",
    "generate.bgsound" : "Add this <em>\"{1}\"</em> sound to the <em>Stage</em>.",
    "generate.addtblock" : "Add this <em>\"{1}\"</em> TynkerBlock (pre-made actor) to the <em>Stage</em>.",
    "generate.addsprite" : "Add this <em>\"{1}\"</em> actor to the <em>Stage</em>.",
    "generate.addcostume" : "Add this <em>\"{1}\"</em> costume to <em>\"{2}\"</em> actor.",
    "generate.addsound" : "Add this <em>\"{1}\"</em> sound to <em>\"{2}\"</em> actor.",
    "generate.property" : "Change the \"{1}\" property of \"{2}\" to <em class=\"value\">{3}</em> in the properties.",
    "generate.label" : "Add the <em class=\"block\">{1}</em> block to <em>{2}</em>'s code.",
    "generate.addtolabelsocket" : "Add the <em class=\"block\">{1}</em> block into the <em class=\"block\">{2}</em> block in <em>{3}</em>'s code.",
    "generate.addtoblocksocket" : "Add the <em class=\"block\">{1}</em> block into the <em class=\"block\">{2}</em> block in <em>{3}</em>'s code.",
    "generate.setvaluemultiple" : "Set the {1} value of the <em class=\"block\">{2}</em> block to <em class=\"value\">{3}</em> in <em>{4}</em>'s code.",
    "generate.setvalue" : "Set the value of the <em class=\"block\">{1}</em> block to <em class=\"value\">{2}</em> in <em>{3}</em>'s code.",
    "generate.block" : "Add the <em class=\"block\">{1}</em> block to <em>{2}</em>'s code.",
    "generate.blockcontainer" : "Add the <em class=\"block\">{1}</em> block into the <em class=\"block\">{2}</em> block in <em>{3}</em>'s code.",
    "generate.blocknext" : "Add the <em class=\"block\">{1}</em> block to the <em class=\"block\">{2}</em> block in <em>{3}</em>'s code.",
    "generate.addblank" : "Add a blank actor to the stage.",
    "dialog.functiontitle" : "Define Function",
    "dialog.loadprojtitle" : "Select a Project",
    "dialog.projectloading" : "Loading... Please wait...",
    "dialog.loadlessontitle" : "Select a Tutorial",
    "dialog.lessonloading" : "Loading... Please wait...",
    "dialog.defaultprojdesc" : "",
    "dialog.savetitle" : "Save Project",
    "dialog.edittitle" : "Edit Project Details",
    "dialog.submittitle" : "Submit Entry",
    "dialog.actormissingerrtitle" : "Missing Documentation",
    "dialog.actormissingerrtext" : "Please fill in all documentation for the actor",
    "dialog.actorconfirmoverwrite" : "This actor was already saved. Should I overwrite or save as a new actor?",
    "dialog.edittagsdescription" : "Enter tags for this block separated by commas",
    "dialog.btndone" : "Done",
    "dialog.btncontinue" : "Continue",
    "dialog.btnreplay" : "Replay",
    "dialog.btnreplaylesson" : "Replay Lesson",
    "dialog.btnclose" : "Close",
    "dialog.btnok" : "OK",
    "dialog.btnnext" : "Next",
    "dialog.btnprev" : "Previous",
    "dialog.btntryitout" : "Try It Out",
    "dialog.btnimport" : "Import",
    "dialog.btncancel" : "Cancel",
    "dialog.btnsave" : "Save",
    "dialog.btnsavedeploy" : "Save &amp; Deploy",
    "dialog.btnsavenew" : "Save as New",
    "dialog.btnyes" : "Yes",
    "dialog.btnno" : "No",
    "dialog.btndiscard" : "Cancel",
    "dialog.btndelete" : "Delete",
    "dialog.btnadd" : "Add",
    "dialog.btnaddcostume" : "Add Costume",
    "dialog.btnaddbackground" : "Add Background",
    "dialog.btnaddcount" : "Add ({1})",
    "dialog.btncreate" : "Create",
    "dialog.btnaddscene" : "Add Background",
    "dialog.btnaddsound" : "Add Sound",
    "dialog.btneditavatar" : "Edit Character",
    "dialog.btnrecord" : "Record Sound",
    "dialog.btnsubmit" : "Submit",
    "dialog.btnunsubmit" : "Remove Submission",
    "paint.title" : "Edit this Image",
    "paint.drop_zone" : "Drop files here",
    "paint.tool_pencil" : "铅笔",
    "paint.tool_brush": "刷子",
    "paint.tool_pen": "钢笔",
    "paint.tool_eraser": "橡皮擦",
    "paint.tool_fill": "油漆桶",
    "paint.tool_shape": "画形状工具",
    "paint.tool_rectangle" : "矩形工具",
    "paint.tool_ellipse" : "椭圆形工具",
    "paint.tool_line" : "线条工具",
    "paint.tool_text" : "文本",
    "paint.tool_selection" : "选择工具",
    "paint.tool_stamping" : "印花工具",
    "paint.tool_zoom" : "缩放",
    "paint.tool_center": "选择角色中心点",
    "paint.tool_eyedropper": "颜色拾取工具",
    "paint.tool_selbox": "矩形选区",
    "paint.tool_selellipse": "椭圆形选区",
    "paint.tool_sellasso": "套索选择",
    "paint.tool_fliphorz" : "水平翻转",
    "paint.tool_flipvert": "垂直翻转",
    "paint.tool_grow" : "放大",
    "paint.tool_shrink" : "缩小",
    "paint.undo" : "撤销",
    "paint.redo" : "重做",
    "paint.cut" : "剪切",
    "paint.copy" : "复制",
    "paint.paste" : "粘贴",
    "paint.menu_edit" : "编辑",
    "paint.menu_import" : "导入图像",
    "paint.menu_importmedia" : "从媒体库导入",
    "paint.menu_clear" : "清空画布",
    "paint.menu_fliphorz": "水平翻转画布",
    "paint.menu_flipvert": "垂直翻转画布",
    //"paint.menu_showcenter" : "Show Actor Center Point",
    //"paint.menu_hidecenter" : "Hide Actor Center Point",
    //"paint.menu_showgrid" : "Show Grid",
    //"paint.menu_hidegrid" : "Hide Grid",
    "paint.menu_showcenter": "显示角色中心点",
    "paint.menu_hidecenter": "隐藏角色中心点",
    "paint.menu_showgrid": "显示网格",
    "paint.menu_hidegrid": "隐藏网格",
    "paint.menu_font" : "Font",
    "paint.menu_fontsize" : "Font Size",
    "app.title" : "Tynker",
    "app.dashboard.student.create" : "My Projects",
    "app.dashboard.student.explore" : "Explore",
    "app.dashboard.student.help" : "Help",
    "app.dashboard.student.launchpad" : "Launchpad",
    "app.dashboard.student.learn" : "Learn to Code",
    "app.dashboard.student.logout" : "Sign Out",
    "app.dashboard.student.minecraft" : "Minecraft",
    "app.dashboard.student.restart" : "Restart Activities",
    "app.dashboard.student.reset" : "Reset Progress",
    "site.about_tynker" : "Tynker is a creative computing platform where millions of kids have learned to program and built games, apps and more. Tynker offers self-paced online courses for children to learn coding at home, as well as an engaging programming curriculum for schools.",
    "site.about_tynker_parent" : "Tynker offers interactive courses for children to learn programming at their own pace at home.",
    "site.about_tynker_student" : "Make your own games, animations, stories and more using easy drag and drop visual programming.",
    "site.million_kids" : "50",
    "site.thousand_schools" : "60",
    "site.sign_in" : "Sign In",
    "site.sign_up" : "Join for Free",
    "site.shop" : "Home Courses",
    "site.shop_cta" : "Browse Courses",
    "site.shop_cta_alternate" : "Enroll Today",
    "site.shop_cta_hard" : "Get Started",
    "site.shop_cta_soft" : "Learn More",
    "site.store.qualifies_multi_child_discount" : "Your purchase qualifies for a multi-child discount. Please contact us at support@tynker.com for your discount",
    "site.store.checkout" : "Checkout Now",
    "site.title" : "Coding for Kids | Tynker",
    "site.title_format" : "%s | %s | Tynker",
    "site.errors.invalid_email" : "That doesn't look like a valid email",
    "site.errors.user_exists" : "Welcome back! The email you entered has an active account. Please login as a returning customer or enter a new email.",
    "site.courses.requirements" : "Online courses require a desktop computer, laptop computer, Chromebook, or Netbook with Internet connection and a Chrome (29+), Firefox (30+), Safari (7+), or Internet Explorer (10+) browser. No downloads required. Courses are not supported on tablets.",
    "site.minecraft.requirements" : "Minecraft courses and server access is available to verified accounts. Minecraft for PC or Mac (not Pocket Edition) with a Minecraft account is required for server access. Content and courses are subject to changes. NOT AN OFFICIAL MINECRAFT PRODUCT. NOT APPROVED BY OR ASSOCIATED WITH MOJANG.",
    "site.drone.requirements" : "The Stunt Pilot course requires a physical drone and an Ipad or Android tablet (each sold separately). Any airborne Parrot Minidrone such as the <a target=\"_blank\" href=\"https://www.amazon.com/Parrot-MiniDrone-Rolling-Spider-White/dp/B00KZM53ZK\">Rolling Spider</a>, <a target=\"_blank\" href=\"https://www.parrot.com/us/minidrones/parrot-airborne-night-maclane#parrot-airborne-night-maclane\">Night</a>, <a target=\"_blank\" href=\"https://www.amazon.com/Parrot-Airborne-Cargo-MiniDrone-Travis/dp/B0111O7VIC/\">Cargo</a>, <a target=\"_blank\" href=\"https://www.parrot.com/us/minidrones/parrot-mambo#parrot-mambo-\">Mambo</a>, or <a target=\"_blank\" href=\"https://www.parrot.com/us/minidrones/parrot-Swing#parrot-swing\">Swing</a> drone can be used.",
    "site.school.courses.requirements" : "Online courses and lesson plans require a desktop computer, laptop computer, Chromebook, or Netbook with Internet connection and a Chrome (29+), Firefox (30+), Safari (7+), or Internet Explorer (10+) browser. No downloads required. Courses and classroom management are not supported on tablets.",
};
